name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 修改为写权限以允许推送到 gh-pages 分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build:h5-netlify
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # 使用不同的部署 action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true  # 创建孤立分支，不保留历史记录